### ISSUE TITLE
Discuss diffuse user name use case behavior

### ISSUE THREAD

**Issue by Rob174** [nsmaniotto/Distributed-Chat-System#1]
- Are we going to periodically broadcast our current User informations ?
   - if yes is it mandatory to use two threads ? (i think yes but in that case we need to modify the architecture)
   - if no how a newly logged-in user can get to know us ?

**Comment by nsmaniotto** [comment]
As I see it, each agent must announce its personnal presence, regularly (every 5 seconds I'd say), otherwise the information must be centralized and maybe only one agent would have to broadcast but this would go against our architecture (imagine if this dedicated agent would shut down right before its scheduled broadcast).

Using multicast as mentionned would allow this strategy (every agent announces its presence regularly) not to use the network unnecessarily and too often.
